// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/noamcattan/geni/ent/account"
	"github.com/noamcattan/geni/ent/category"
	"github.com/noamcattan/geni/ent/predicate"
	"github.com/noamcattan/geni/ent/user"
)

// AccountUpdate is the builder for updating Account entities.
type AccountUpdate struct {
	config
	hooks    []Hook
	mutation *AccountMutation
}

// Where appends a list predicates to the AccountUpdate builder.
func (au *AccountUpdate) Where(ps ...predicate.Account) *AccountUpdate {
	au.mutation.Where(ps...)
	return au
}

// SetName sets the "name" field.
func (au *AccountUpdate) SetName(s string) *AccountUpdate {
	au.mutation.SetName(s)
	return au
}

// SetSheetsCredentials sets the "sheets_credentials" field.
func (au *AccountUpdate) SetSheetsCredentials(b []byte) *AccountUpdate {
	au.mutation.SetSheetsCredentials(b)
	return au
}

// ClearSheetsCredentials clears the value of the "sheets_credentials" field.
func (au *AccountUpdate) ClearSheetsCredentials() *AccountUpdate {
	au.mutation.ClearSheetsCredentials()
	return au
}

// SetSpreadsheetID sets the "spreadsheet_id" field.
func (au *AccountUpdate) SetSpreadsheetID(s string) *AccountUpdate {
	au.mutation.SetSpreadsheetID(s)
	return au
}

// SetNillableSpreadsheetID sets the "spreadsheet_id" field if the given value is not nil.
func (au *AccountUpdate) SetNillableSpreadsheetID(s *string) *AccountUpdate {
	if s != nil {
		au.SetSpreadsheetID(*s)
	}
	return au
}

// ClearSpreadsheetID clears the value of the "spreadsheet_id" field.
func (au *AccountUpdate) ClearSpreadsheetID() *AccountUpdate {
	au.mutation.ClearSpreadsheetID()
	return au
}

// AddMemberIDs adds the "member" edge to the User entity by IDs.
func (au *AccountUpdate) AddMemberIDs(ids ...int) *AccountUpdate {
	au.mutation.AddMemberIDs(ids...)
	return au
}

// AddMember adds the "member" edges to the User entity.
func (au *AccountUpdate) AddMember(u ...*User) *AccountUpdate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return au.AddMemberIDs(ids...)
}

// AddCategoryIDs adds the "categories" edge to the Category entity by IDs.
func (au *AccountUpdate) AddCategoryIDs(ids ...int) *AccountUpdate {
	au.mutation.AddCategoryIDs(ids...)
	return au
}

// AddCategories adds the "categories" edges to the Category entity.
func (au *AccountUpdate) AddCategories(c ...*Category) *AccountUpdate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return au.AddCategoryIDs(ids...)
}

// Mutation returns the AccountMutation object of the builder.
func (au *AccountUpdate) Mutation() *AccountMutation {
	return au.mutation
}

// ClearMember clears all "member" edges to the User entity.
func (au *AccountUpdate) ClearMember() *AccountUpdate {
	au.mutation.ClearMember()
	return au
}

// RemoveMemberIDs removes the "member" edge to User entities by IDs.
func (au *AccountUpdate) RemoveMemberIDs(ids ...int) *AccountUpdate {
	au.mutation.RemoveMemberIDs(ids...)
	return au
}

// RemoveMember removes "member" edges to User entities.
func (au *AccountUpdate) RemoveMember(u ...*User) *AccountUpdate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return au.RemoveMemberIDs(ids...)
}

// ClearCategories clears all "categories" edges to the Category entity.
func (au *AccountUpdate) ClearCategories() *AccountUpdate {
	au.mutation.ClearCategories()
	return au
}

// RemoveCategoryIDs removes the "categories" edge to Category entities by IDs.
func (au *AccountUpdate) RemoveCategoryIDs(ids ...int) *AccountUpdate {
	au.mutation.RemoveCategoryIDs(ids...)
	return au
}

// RemoveCategories removes "categories" edges to Category entities.
func (au *AccountUpdate) RemoveCategories(c ...*Category) *AccountUpdate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return au.RemoveCategoryIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (au *AccountUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(au.hooks) == 0 {
		affected, err = au.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AccountMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			au.mutation = mutation
			affected, err = au.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(au.hooks) - 1; i >= 0; i-- {
			if au.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = au.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, au.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (au *AccountUpdate) SaveX(ctx context.Context) int {
	affected, err := au.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (au *AccountUpdate) Exec(ctx context.Context) error {
	_, err := au.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (au *AccountUpdate) ExecX(ctx context.Context) {
	if err := au.Exec(ctx); err != nil {
		panic(err)
	}
}

func (au *AccountUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   account.Table,
			Columns: account.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: account.FieldID,
			},
		},
	}
	if ps := au.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := au.mutation.Name(); ok {
		_spec.SetField(account.FieldName, field.TypeString, value)
	}
	if value, ok := au.mutation.SheetsCredentials(); ok {
		_spec.SetField(account.FieldSheetsCredentials, field.TypeBytes, value)
	}
	if au.mutation.SheetsCredentialsCleared() {
		_spec.ClearField(account.FieldSheetsCredentials, field.TypeBytes)
	}
	if value, ok := au.mutation.SpreadsheetID(); ok {
		_spec.SetField(account.FieldSpreadsheetID, field.TypeString, value)
	}
	if au.mutation.SpreadsheetIDCleared() {
		_spec.ClearField(account.FieldSpreadsheetID, field.TypeString)
	}
	if au.mutation.MemberCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.MemberTable,
			Columns: []string{account.MemberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.RemovedMemberIDs(); len(nodes) > 0 && !au.mutation.MemberCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.MemberTable,
			Columns: []string{account.MemberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.MemberIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.MemberTable,
			Columns: []string{account.MemberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if au.mutation.CategoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   account.CategoriesTable,
			Columns: account.CategoriesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: category.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.RemovedCategoriesIDs(); len(nodes) > 0 && !au.mutation.CategoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   account.CategoriesTable,
			Columns: account.CategoriesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: category.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.CategoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   account.CategoriesTable,
			Columns: account.CategoriesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: category.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, au.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{account.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// AccountUpdateOne is the builder for updating a single Account entity.
type AccountUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccountMutation
}

// SetName sets the "name" field.
func (auo *AccountUpdateOne) SetName(s string) *AccountUpdateOne {
	auo.mutation.SetName(s)
	return auo
}

// SetSheetsCredentials sets the "sheets_credentials" field.
func (auo *AccountUpdateOne) SetSheetsCredentials(b []byte) *AccountUpdateOne {
	auo.mutation.SetSheetsCredentials(b)
	return auo
}

// ClearSheetsCredentials clears the value of the "sheets_credentials" field.
func (auo *AccountUpdateOne) ClearSheetsCredentials() *AccountUpdateOne {
	auo.mutation.ClearSheetsCredentials()
	return auo
}

// SetSpreadsheetID sets the "spreadsheet_id" field.
func (auo *AccountUpdateOne) SetSpreadsheetID(s string) *AccountUpdateOne {
	auo.mutation.SetSpreadsheetID(s)
	return auo
}

// SetNillableSpreadsheetID sets the "spreadsheet_id" field if the given value is not nil.
func (auo *AccountUpdateOne) SetNillableSpreadsheetID(s *string) *AccountUpdateOne {
	if s != nil {
		auo.SetSpreadsheetID(*s)
	}
	return auo
}

// ClearSpreadsheetID clears the value of the "spreadsheet_id" field.
func (auo *AccountUpdateOne) ClearSpreadsheetID() *AccountUpdateOne {
	auo.mutation.ClearSpreadsheetID()
	return auo
}

// AddMemberIDs adds the "member" edge to the User entity by IDs.
func (auo *AccountUpdateOne) AddMemberIDs(ids ...int) *AccountUpdateOne {
	auo.mutation.AddMemberIDs(ids...)
	return auo
}

// AddMember adds the "member" edges to the User entity.
func (auo *AccountUpdateOne) AddMember(u ...*User) *AccountUpdateOne {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return auo.AddMemberIDs(ids...)
}

// AddCategoryIDs adds the "categories" edge to the Category entity by IDs.
func (auo *AccountUpdateOne) AddCategoryIDs(ids ...int) *AccountUpdateOne {
	auo.mutation.AddCategoryIDs(ids...)
	return auo
}

// AddCategories adds the "categories" edges to the Category entity.
func (auo *AccountUpdateOne) AddCategories(c ...*Category) *AccountUpdateOne {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return auo.AddCategoryIDs(ids...)
}

// Mutation returns the AccountMutation object of the builder.
func (auo *AccountUpdateOne) Mutation() *AccountMutation {
	return auo.mutation
}

// ClearMember clears all "member" edges to the User entity.
func (auo *AccountUpdateOne) ClearMember() *AccountUpdateOne {
	auo.mutation.ClearMember()
	return auo
}

// RemoveMemberIDs removes the "member" edge to User entities by IDs.
func (auo *AccountUpdateOne) RemoveMemberIDs(ids ...int) *AccountUpdateOne {
	auo.mutation.RemoveMemberIDs(ids...)
	return auo
}

// RemoveMember removes "member" edges to User entities.
func (auo *AccountUpdateOne) RemoveMember(u ...*User) *AccountUpdateOne {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return auo.RemoveMemberIDs(ids...)
}

// ClearCategories clears all "categories" edges to the Category entity.
func (auo *AccountUpdateOne) ClearCategories() *AccountUpdateOne {
	auo.mutation.ClearCategories()
	return auo
}

// RemoveCategoryIDs removes the "categories" edge to Category entities by IDs.
func (auo *AccountUpdateOne) RemoveCategoryIDs(ids ...int) *AccountUpdateOne {
	auo.mutation.RemoveCategoryIDs(ids...)
	return auo
}

// RemoveCategories removes "categories" edges to Category entities.
func (auo *AccountUpdateOne) RemoveCategories(c ...*Category) *AccountUpdateOne {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return auo.RemoveCategoryIDs(ids...)
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (auo *AccountUpdateOne) Select(field string, fields ...string) *AccountUpdateOne {
	auo.fields = append([]string{field}, fields...)
	return auo
}

// Save executes the query and returns the updated Account entity.
func (auo *AccountUpdateOne) Save(ctx context.Context) (*Account, error) {
	var (
		err  error
		node *Account
	)
	if len(auo.hooks) == 0 {
		node, err = auo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AccountMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			auo.mutation = mutation
			node, err = auo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(auo.hooks) - 1; i >= 0; i-- {
			if auo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = auo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, auo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Account)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from AccountMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (auo *AccountUpdateOne) SaveX(ctx context.Context) *Account {
	node, err := auo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (auo *AccountUpdateOne) Exec(ctx context.Context) error {
	_, err := auo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (auo *AccountUpdateOne) ExecX(ctx context.Context) {
	if err := auo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (auo *AccountUpdateOne) sqlSave(ctx context.Context) (_node *Account, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   account.Table,
			Columns: account.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: account.FieldID,
			},
		},
	}
	id, ok := auo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Account.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := auo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, account.FieldID)
		for _, f := range fields {
			if !account.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != account.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := auo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := auo.mutation.Name(); ok {
		_spec.SetField(account.FieldName, field.TypeString, value)
	}
	if value, ok := auo.mutation.SheetsCredentials(); ok {
		_spec.SetField(account.FieldSheetsCredentials, field.TypeBytes, value)
	}
	if auo.mutation.SheetsCredentialsCleared() {
		_spec.ClearField(account.FieldSheetsCredentials, field.TypeBytes)
	}
	if value, ok := auo.mutation.SpreadsheetID(); ok {
		_spec.SetField(account.FieldSpreadsheetID, field.TypeString, value)
	}
	if auo.mutation.SpreadsheetIDCleared() {
		_spec.ClearField(account.FieldSpreadsheetID, field.TypeString)
	}
	if auo.mutation.MemberCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.MemberTable,
			Columns: []string{account.MemberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.RemovedMemberIDs(); len(nodes) > 0 && !auo.mutation.MemberCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.MemberTable,
			Columns: []string{account.MemberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.MemberIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.MemberTable,
			Columns: []string{account.MemberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if auo.mutation.CategoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   account.CategoriesTable,
			Columns: account.CategoriesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: category.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.RemovedCategoriesIDs(); len(nodes) > 0 && !auo.mutation.CategoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   account.CategoriesTable,
			Columns: account.CategoriesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: category.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.CategoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   account.CategoriesTable,
			Columns: account.CategoriesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: category.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Account{config: auo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, auo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{account.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
