// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/noamcattan/geni/ent/category"
	"github.com/noamcattan/geni/ent/expense"
)

// ExpenseCreate is the builder for creating a Expense entity.
type ExpenseCreate struct {
	config
	mutation *ExpenseMutation
	hooks    []Hook
}

// SetCreateTime sets the "create_time" field.
func (ec *ExpenseCreate) SetCreateTime(t time.Time) *ExpenseCreate {
	ec.mutation.SetCreateTime(t)
	return ec
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (ec *ExpenseCreate) SetNillableCreateTime(t *time.Time) *ExpenseCreate {
	if t != nil {
		ec.SetCreateTime(*t)
	}
	return ec
}

// SetAmount sets the "amount" field.
func (ec *ExpenseCreate) SetAmount(f float64) *ExpenseCreate {
	ec.mutation.SetAmount(f)
	return ec
}

// SetDescription sets the "description" field.
func (ec *ExpenseCreate) SetDescription(s string) *ExpenseCreate {
	ec.mutation.SetDescription(s)
	return ec
}

// AddCategoryIDs adds the "category" edge to the Category entity by IDs.
func (ec *ExpenseCreate) AddCategoryIDs(ids ...int) *ExpenseCreate {
	ec.mutation.AddCategoryIDs(ids...)
	return ec
}

// AddCategory adds the "category" edges to the Category entity.
func (ec *ExpenseCreate) AddCategory(c ...*Category) *ExpenseCreate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return ec.AddCategoryIDs(ids...)
}

// Mutation returns the ExpenseMutation object of the builder.
func (ec *ExpenseCreate) Mutation() *ExpenseMutation {
	return ec.mutation
}

// Save creates the Expense in the database.
func (ec *ExpenseCreate) Save(ctx context.Context) (*Expense, error) {
	var (
		err  error
		node *Expense
	)
	if err := ec.defaults(); err != nil {
		return nil, err
	}
	if len(ec.hooks) == 0 {
		if err = ec.check(); err != nil {
			return nil, err
		}
		node, err = ec.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ExpenseMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = ec.check(); err != nil {
				return nil, err
			}
			ec.mutation = mutation
			if node, err = ec.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(ec.hooks) - 1; i >= 0; i-- {
			if ec.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ec.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, ec.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Expense)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from ExpenseMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (ec *ExpenseCreate) SaveX(ctx context.Context) *Expense {
	v, err := ec.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ec *ExpenseCreate) Exec(ctx context.Context) error {
	_, err := ec.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ec *ExpenseCreate) ExecX(ctx context.Context) {
	if err := ec.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ec *ExpenseCreate) defaults() error {
	if _, ok := ec.mutation.CreateTime(); !ok {
		if expense.DefaultCreateTime == nil {
			return fmt.Errorf("ent: uninitialized expense.DefaultCreateTime (forgotten import ent/runtime?)")
		}
		v := expense.DefaultCreateTime()
		ec.mutation.SetCreateTime(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (ec *ExpenseCreate) check() error {
	if _, ok := ec.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "Expense.create_time"`)}
	}
	if _, ok := ec.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "Expense.amount"`)}
	}
	if _, ok := ec.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "Expense.description"`)}
	}
	return nil
}

func (ec *ExpenseCreate) sqlSave(ctx context.Context) (*Expense, error) {
	_node, _spec := ec.createSpec()
	if err := sqlgraph.CreateNode(ctx, ec.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (ec *ExpenseCreate) createSpec() (*Expense, *sqlgraph.CreateSpec) {
	var (
		_node = &Expense{config: ec.config}
		_spec = &sqlgraph.CreateSpec{
			Table: expense.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: expense.FieldID,
			},
		}
	)
	if value, ok := ec.mutation.CreateTime(); ok {
		_spec.SetField(expense.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := ec.mutation.Amount(); ok {
		_spec.SetField(expense.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := ec.mutation.Description(); ok {
		_spec.SetField(expense.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if nodes := ec.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   expense.CategoryTable,
			Columns: expense.CategoryPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: category.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ExpenseCreateBulk is the builder for creating many Expense entities in bulk.
type ExpenseCreateBulk struct {
	config
	builders []*ExpenseCreate
}

// Save creates the Expense entities in the database.
func (ecb *ExpenseCreateBulk) Save(ctx context.Context) ([]*Expense, error) {
	specs := make([]*sqlgraph.CreateSpec, len(ecb.builders))
	nodes := make([]*Expense, len(ecb.builders))
	mutators := make([]Mutator, len(ecb.builders))
	for i := range ecb.builders {
		func(i int, root context.Context) {
			builder := ecb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ExpenseMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ecb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ecb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ecb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ecb *ExpenseCreateBulk) SaveX(ctx context.Context) []*Expense {
	v, err := ecb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ecb *ExpenseCreateBulk) Exec(ctx context.Context) error {
	_, err := ecb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ecb *ExpenseCreateBulk) ExecX(ctx context.Context) {
	if err := ecb.Exec(ctx); err != nil {
		panic(err)
	}
}
