// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Account is the predicate function for account builders.
type Account func(*sql.Selector)

// Category is the predicate function for category builders.
type Category func(*sql.Selector)

// Expense is the predicate function for expense builders.
type Expense func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
